### ISSUE TITLE
JSONDecoder Error on Mac and Rasperry / Python 3

### ISSUE THREAD

**Issue by davidohne** [srujanpatil/nrc2strava#5]
Hi!
Thanks for this great app.
I'm getting this error on mac and on my raspberry pi :(

```
100  404k    0  404k    0     0   627k      0 --:--:-- --:--:-- --:--:--  627k
127.0.0.1 - - [19/Apr/2020 13:49:07] "GET /select?state=&code=ee59c593ce7ff36e8f7efad478b0880c6e08bf97&scope=read,activity:write HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
StopIteration: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/david/nrc2strava/app/server.py", line 57, in select
    err = nike_client.json2gpx()
  File "/Users/david/nrc2strava/app/runner.py", line 35, in json2gpx
    data = extract(file)
  File "/Users/david/nrc2strava/app/extract.py", line 13, in extract
    data = json.load(f)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
127.0.0.1 - - [19/Apr/2020 13:49:07] "GET /select?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2020 13:49:07] "GET /select?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2020 13:49:07] "GET /select?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2020 13:49:07] "GET /select?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [19/Apr/2020 13:49:08] "GET /select?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

```

Don't know what I'm doing wrong.

**Comment by mrsruj** [comment]
It looks like a decoding error to me. Can you check the particular JSON file which is causing this error?

**Comment by engineervix** [comment]
I also encountered this error. After further investigation, I discovered that this was because of calling `os.listdir()` on a directory which included non-JSON files (`.gitkeep`). I opened a pull request (#6) which fixes this.

**Comment by mrsruj** [comment]
Thanks for pointing this out. @engineervix
